### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Justineo** [ecomfe/oo#26]
我们的开源项目应该都是基于 BSD 的，现在 `oo` 的 `package.json` 里用了 GPL，改掉吧不然不好搞了……

**Comment by otakustay** [comment]
怎么着也别用GPL，病毒协议太可怕了……

我有些库是lGPL的，我觉得只要比BSD限制少的都没问题，但GPL实在是太那啥，等于我们的业务系统都是要开源的了

**Comment by Exodia** [comment]
···还没注意这个。。npm init 一下，估计回车按太快了。。
