### ISSUE TITLE
基于类 weakmap 的私有成员实现

### ISSUE THREAD

**Issue by Exodia** [ecomfe/oo#30]
实现见:  https://github.com/ecomfe/oo/tree/feature/private-weakmap-like

使用方式如下：

```javascript
// User.js
var $private = oo.createPrivate({
      privateMethod: function () {
            // 获取私有属性
             return $private(this).privateProp;
      },
      privateProp: 'private'
}); 

var exports = {
      constructor: function () {
             this.$super(arguments);
            // 设置实例上的私有属性
           $private(this).instancePrivateProp = 'instance';
      },
      publicMethod: function () {
           // 调用私有方法
            var result = $private(this).privateMethod.call(this);
           return result + $private(this).instancePrivateProp;  
      }
};

var User = oo.create(exports);

```

优点在于：

- 兼容性好，ie系，严格模式都可以正常运行。

- 性能应该也不错，内部不是用 weakmap，而是在实例上挂个uid，通过 uid 去找对应的私有成员，应该会比 symbol 更快。

- 基于此实现 protect 特性很容易。

不足在于：

- 写法可能有点不舒服，调用私有方法必须用 call 去改变作用域到实例上

- 不如 property 和 symbol 的方式来得直观

- 私有方法可能用闭包会比这种方式来得省事，但该方案更适合于需要在实例上挂私有属性的场景。

@otakustay @Justineo 我个人倾向于用类 weakmap 的实现方案

**Comment by otakustay** [comment]
此类方式在没有原生`WeakMap`的支持的情况下，是不是会导致对象无法GC回收？

**Comment by Exodia** [comment]
> 此类方式在没有原生WeakMap的支持的情况下，是不是会导致对象无法GC回收？

不会，内部的 store 实现是通过 obj.__eooInstanceToken__去做的索引，不和 obj 关联，token 是个唯一数字或者字符串。而且不倾向用真正的 weakMap 去做，因为据说 weakMap内部是顺序比较对象键去匹配的，时间复杂度为o(n).

我这的实现大概是这样的： 

```javascript
var store = {};   
var getPrivate = function (instance) {
       return store[instance.__eooInstanceToken];
};

```

**Comment by otakustay** [comment]
我不是指类的实例本身无法回收，而是这个实例的私有成员在实例本身回收后，依旧会被这个Map存储而无法GC

比如在类的构造函数中有`$private(this).instancePrivateProp = new VeryLargeObject('100MB');`，在这个实例本身GC后，这个100MB的`VeryLargeObject`会怎么样？

**Comment by Exodia** [comment]
理解错了-_-||，确实不能被回收，我把存储对象改成挂在实例上吧

**Comment by Exodia** [comment]
调整好了：
https://github.com/ecomfe/oo/commit/a660c0a8907818ce238766ee79ed04eab860d4bf
